import type { Metadata } from "next";
import SidebarCard from "@/components/global/sidebar/sidebar.card";
import Header from "@/components/global/header/header";
import { ThemeProvider } from 'next-themes';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider attribute="class">
      <div 
      >
        <div className="min-h-screen flex relative">
      <div className="min-h-screen">
      <div className="fixed top-0 left-0 z-40">
        <SidebarCard />
      </div>

      <div className="ml-64">
        <div >
          <Header />
        </div>

        <div>
          {children}
        </div>
      </div>
      </div>
    </div>
      </div>
      </ThemeProvider>
  );
}
