
import type { Metadata } from "next";
import {Poppins, Lexend, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChakraProvider } from "@chakra-ui/react";
import themeSystem from "configs/chakra.config";
import { ThemeProvider } from 'next-themes';




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const lexend = Lexend({
  subsets: ['latin'],
  variable: '--font-lex',
});

export const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-pop',
  weight: "100"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} ${poppins.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <ChakraProvider value={themeSystem}> {/* Make sure you're passing theme here */}
            {children}
          </ChakraProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}