import type { Metadata } from "next";
import { Geist, Geist_Mono, Lexend } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { ReactQueryProvider } from "@/lib/react-query-provider";
import { LoadingSpinner } from "@/components/global/login/loading";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lexend = Lexend({
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} antialiased`}
      >
        <ReactQueryProvider>
          <Suspense fallback={<LoadingSpinner fullPage={true} />}>
          {children}
        </Suspense>
        <Toaster richColors position="top-right" />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
