
import type { Metadata } from "next";
import {Poppins, Lexend, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Box, ChakraProvider, Flex } from "@chakra-ui/react";
import themeSystem from "configs/chakra.config";
import { ThemeProvider } from 'next-themes';
import Sidebar from "components/Sidebar/Sidebar";
import NotificationBell from "components/DashboardLayout/NotificationBell";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const lexend = Lexend({
  subsets: ['latin'],
  variable: '--font-lex',
});

export const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-pop',
  weight: "100"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} ${poppins.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <ChakraProvider value={themeSystem}> 
          <Flex h="100vh">
  {/* Sidebar */}
  <Box w="250px">
    <Sidebar />
  </Box>


  <Box flex="1" ml={"50px"}>
    <NotificationBell />
    <Box p={4}>
      {children}
    </Box>
  </Box>
</Flex>

          </ChakraProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}